"""Pydantic models describing outgoing API responses.

These models define the contract that the Gemini AI response is validated
against, plus the deterministic static-analysis and top-level API response
wrappers.
"""
from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class BugType(str, Enum):
    SYNTAX = "syntax"
    RUNTIME = "runtime"
    LOGIC = "logic"
    EDGE_CASE = "edge_case"
    PERFORMANCE = "performance"
    SECURITY = "security"
    QUALITY = "quality"


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Bug(BaseModel):
    title: str
    type: BugType
    severity: Severity
    line: int | None = Field(default=None, description="1-indexed line number, or null if unknown")
    verified: bool = Field(
        default=False,
        description="True if confirmed by deterministic static analysis, false if AI-suggested only",
    )
    problem: str
    explanation: str
    suggested_fix: str


class AnalysisStatus(str, Enum):
    SUCCESS = "success"
    PARTIAL = "partial"
    ERROR = "error"


class StaticAnalysisFinding(BaseModel):
    """A single deterministic (non-AI) finding from a language analyzer."""

    title: str
    severity: Severity
    line: int | None = None
    message: str


class StaticAnalysisResult(BaseModel):
    """Result of the deterministic static-analysis stage."""

    language: str
    syntax_valid: bool
    findings: list[StaticAnalysisFinding] = Field(default_factory=list)
    # True when this language has real static analysis (currently Python only).
    fully_supported: bool = False


class MentorAnalysis(BaseModel):
    """The structured response produced (and validated) from the Gemini model."""

    language: str
    summary: str
    code_quality_score: int = Field(..., ge=0, le=100)
    analysis_status: AnalysisStatus = AnalysisStatus.SUCCESS

    bugs: list[Bug] = Field(default_factory=list)
    strengths: list[str] = Field(default_factory=list)

    fixed_code: str = ""
    changes: list[str] = Field(default_factory=list)

    tests: str = ""
    test_explanations: list[str] = Field(default_factory=list)

    edge_cases: list[str] = Field(default_factory=list)

    learning_points: list[str] = Field(default_factory=list)
    next_exercise: str = ""


class AnalyzeResponse(BaseModel):
    """Top-level API response returned to the frontend."""

    static_analysis: StaticAnalysisResult
    mentor: MentorAnalysis
    disclaimer: str = (
        "The code quality score and AI-suggested findings are generated by an "
        "LLM and are not an absolute measurement. Only findings marked "
        "'verified' were confirmed by deterministic static analysis."
    )


class HintResponse(BaseModel):
    hint: str
    reveal_available: bool = True


class ErrorResponse(BaseModel):
    error: str
    detail: str | None = None
